"""Human Index 文档渲染层（确定性为主 + 可选 LLM 散文合成）。

设计原则（Phase 8.3）：
- Fact / Inference / Recommendation / Unknown 分离（文档用 [Fact]/[Inference]/
  [Unknown] 标注；confidence 由 scorer 决定，不由 LLM 决定）
- Mermaid 只画 Index/Evidence 支撑的模块依赖边；LLM 不决定"谁调用谁"
- 不存在的 symbol/module 不会出现（渲染只用 bundle 里已存在的节点）
- non_build / third_party 不进"当前固件模块"描述，只显式标注
- 文档顶部带 Index metadata（不重复维护另一套 fingerprint）

本模块只做字符串组装，无 IO（IO/编排在 service.py）。
"""

from __future__ import annotations

from typing import Any

from agentx.human.manifest import (
    DOC_ARCHITECTURE,
    DOC_MODULES,
    DOC_PROJECT_OVERVIEW,
)
from agentx.module.responsibility import RESPONSIBILITIES_FILENAME

# ---------- 公共头 / metadata ----------


def _project_name(root_name: str) -> str:
    return root_name


def metadata_header(index: Any, root_name: str) -> list[str]:
    bi = index.build_info or {}
    bs = bi.get("build_scope") or {}
    ts = (
        index.last_index_time.isoformat()
        if index.last_index_time
        else index.generated_at.isoformat()
    )
    lines = [
        "> Generated by AgentX",
        f"> Index: `{root_name}_codebase_index/index.json`",
        f"> Build Target: `{bs.get('target') or bi.get('target') or 'unknown'}`",
        f"> Index Time: `{ts}`",
        f"> Source Fingerprint: `{index.source_fingerprint or 'unknown'}`",
        f"> Build Scope Fingerprint: `{index.build_scope_fingerprint or 'unknown'}`",
        f"> Scope Fingerprint: `{index.scope_fingerprint or 'unknown'}`",
        "> Status: `VALID`",
    ]
    return lines


def _section(title: str) -> list[str]:
    return ["", f"## {title}"]


def _tag_interpretation(conf: str) -> str:
    """职责/理解类结论的置信度标注（不是 Fact——是模型对证据的解释）。"""
    if conf == "high":
        return "[High：有较强证据的职责判断]"
    if conf == "medium":
        return "[Inference：推断的职责]"
    return "[Low：仅路径/命名构成，未做职责判断]"


def _resolve_label(name: str) -> str:
    """Mermaid 节点标签：模块名可能含特殊字符（.codex_review (non-build)）。"""
    return f'"{name}"'


# ---------- Traceability 表 ----------


def traceability_table(rows: list[tuple[str, str]]) -> list[str]:
    lines = ["", "### Traceability", ""]
    lines.append("| Statement | Evidence |")
    lines.append("|---|---|")
    for stmt, ev in rows:
        lines.append(f"| {stmt} | `{ev}` |")
    return lines


# ---------- PROJECT_OVERVIEW ----------


def render_project_overview(
    bundle: Any,
    index: Any,
    project_root_name: str,
    prose: str = "",
) -> str:
    d = bundle.project_overview_data()
    L: list[str] = []
    L.append(f"# {_project_name(project_root_name)}")
    L.append("")
    L.extend(metadata_header(index, project_root_name))
    L.append("")
    L.append("> AgentX Human Project Knowledge")
    L.append(">")
    L.append("> Generated from current Project Index")

    L += _section("1. Project Summary")
    if prose:
        L.append(prose)
    if d["understanding_summary"]:
        L.append("")
        L.append(f"架构概览（understanding）: {d['understanding_summary']}")
    else:
        L.append("")
        L.append("> 架构概览未建立（project_understanding 缺失）。[Unknown / Needs verification]")

    L += _section("2. Runtime Environment")
    L.append(f"- MCU / CPU: `{d['cpu'] or 'Unknown'}`")
    if d["chip"]:
        L.append(f"- Chip: `{d['chip']}` [Fact]")
    L.append(f"- RTOS: `{d['rtos'] or 'None detected / Unknown'}`"
             + (" [Fact：符号存在]" if d["rtos"] else " [Unknown]"))
    L.append(f"- Defines: `{', '.join(str(x) for x in d['defines']) or 'none'}`")
    L.append(f"- Build System: `{d['build_system']}` (`{d['build_source']}`) [Fact]")

    L += _section("3. Build Reality")
    L.append(f"- Build Target: `{d['target'] or 'unknown'}` [Fact]")
    L.append(f"- Targets: `{', '.join(str(x) for x in d['targets']) or 'unknown'}`")
    L.append(f"- Has Build Config: `{bool(d['has_build_config'])}`")
    L.append(f"- Project files: `{d['file_count']}` [Fact]")
    L.append(f"- Compiled files: `{d['compiled_count']}` [Fact：当前 target 编译]")

    L += _section("4. Major Software Areas")
    L.extend(
        f"- `{a['module']}`: {a['responsibility']} {_tag_interpretation(a['confidence'])}"
        for a in d["core_areas"][:12]
    )

    L += _section("5. Main Entry Points")
    eps = d.get("entry_points") or []
    if eps:
        L.append("| File | Symbol | Confidence | Reason |")
        L.append("|---|---|---|---|")
        for e in eps[:10]:
            L.append(
                f"| `{e['file']}` | `{e['symbol']}` | {e['confidence']} | {e['reason']} |"
            )
    else:
        L.append("> 未发现规则化入口。[Unknown]")

    L += _section("6. Core Modules")
    L.extend(f"- `{m['module']}`: {m['responsibility']}" for m in d["core_areas"][:12])

    L += _section("7. Engineering Characteristics")
    L.append(f"- Module count: `{d['module_count']}` [Fact]")
    L.append(f"- Symbol count: `{d['symbol_count']}` [Fact]")
    L.append(f"- Call edges: `{d['call_edge_count']}` [Fact]")
    L.append(f"- Indirect calls (callbacks/registration): `{d['indirect_call_count']}` [Fact]")
    caps = d.get("capabilities") or {}
    sem = (caps.get("semantic") or {})
    L.append(
        f"- Semantic: `{sem.get('enabled')}`"
        + (f" (parser: {sem.get('parser')})" if sem.get("enabled") else "")
    )

    L += _section("8. Known Limitations / Uncertainty")
    if d["errors"]:
        L.append("- Index errors:")
        L.extend(f"  - `{e[:120]}`" for e in d["errors"][:5])
    if not d["rtos"]:
        L.append("- RTOS 未检测（可能无 RTOS 或符号不可见）")
    if not d["core_areas"]:
        L.append("- 核心功能领域未建立（缺 LLM 职责或 understanding）")
    if not d["entry_points"]:
        L.append("- 未发现规则化入口（可运行 agentx understand 补充）")
    L.append("")

    L += traceability_table(
        [
            ("Build target", f"{d['target'] or '?'} / {d['build_system']}"),
            ("MCU", d["cpu"] or "unknown"),
            ("Chip", d["chip"] or "unknown"),
            ("RTOS", d["rtos"] or "unknown"),
            ("Compiled files", str(d["compiled_count"])),
        ]
    )
    return "\n".join(L) + "\n"


# ---------- ARCHITECTURE ----------


def _mermaid_flow(module_dependencies: list[dict[str, str]], max_nodes: int = 40) -> list[str]:
    """Mermaid 图：只画有依赖证据的模块边。

    nodes：只使用 from/to 中真实出现的模块名（bundle 已保证存在）。
    """
    lines = ["```mermaid", "flowchart TD"]
    nodes: list[str] = []
    seen_node: set[str] = set()
    for d in module_dependencies:
        frm, to = d["from"], d["to"]
        for n in (frm, to):
            if n not in seen_node:
                seen_node.add(n)
                nodes.append(_resolve_label(n))
        if len(seen_node) >= max_nodes:
            break
    if not seen_node:
        return ["（无足够的模块依赖证据，暂不画架构图）"]
    lines.append("    " + "\n    ".join(nodes))
    edge_shown = 0
    for d in module_dependencies:
        frm, to = d["from"], d["to"]
        if frm in seen_node and to in seen_node:
            lines.append(f"    {_resolve_label(frm)} --> {_resolve_label(to)}")
            edge_shown += 1
            if edge_shown >= 80:
                break
    lines.append("```")
    return lines


def render_architecture(
    bundle: Any,
    index: Any,
    project_root_name: str,
    prose: str = "",
) -> str:
    d = bundle.architecture_data()
    L: list[str] = []
    L.append("# System Architecture")
    L.append("")
    L.extend(metadata_header(index, project_root_name))
    L.append("")
    L.append("> AgentX Human Project Knowledge — Architecture")
    L.append(">")
    L.append("> Mermaid 只表示有 Index 依赖证据的关系；虚线关系无证据时不画。")

    L += _section("1. Architecture Overview")
    if prose:
        L.append(prose)
    if d.get("architecture_summary"):
        L.append("")
        L.append(f"架构概览: {d['architecture_summary']} [Inference：来自理解层]")
    else:
        L.append("")
        L.append("> 架构概览未建立。[Unknown / Needs verification]")

    L += _section("2. Runtime Layers")
    L.append("- 应用 / 业务层（project scope）:")
    project_module_names = [m.get("name") for m in d.get("modules", [])]
    L.append(f"  - 模块数: `{len(project_module_names)}` [Fact]")
    L.append("- 第三方 / 中间件（third_party scope）:")
    L.append(f"  - `{', '.join(str(x) for x in d.get('third_party', [])) or 'none'}`")
    L.append("- 仓库中存在但不在当前 target（non_build）:")
    if d.get("non_build_modules"):
        L.append(
            "  - `Present in repository, not part of current build target.`: "
            + ", ".join(f"`{m}`" for m in d["non_build_modules"][:8])
        )
    else:
        L.append("  - (none)")

    L += _section("3. Major Modules")
    for m in d.get("modules", [])[:30]:
        resp = str(m.get("responsibility") or "").strip()
        conf = m.get("confidence", "")
        line = f"- `{m['name']}` ({m.get('type', '?')}, build={m.get('build_status', '?')})"
        if resp:
            line += f": {resp} {_tag_interpretation(conf)}"
        L.append(line)

    L += _section("4. Module Dependencies")
    deps = d.get("module_dependencies", [])
    if deps:
        L.append("| From | To | Weight |")
        L.append("|---|---|---:|")
        for dep in deps[:40]:
            L.append(f"| `{dep['from']}` | `{dep['to']}` | {dep['weight']} |")
    else:
        L.append("> 无模块依赖证据。[Unknown]")

    L += _section("5. Main Execution Paths")
    if d.get("startup_flow"):
        L.append("启动流程（understanding，需人工复核）:")
        L.append(f"`{' -> '.join(str(x) for x in d['startup_flow'][:12])}`")
    eps = d.get("entry_points") or []
    if eps:
        L.append("入口（规则化，Fact）:")
        for e in eps[:8]:
            if isinstance(e, dict):
                L.append(f"- `{e.get('file')}` → `{e.get('symbol')}` [{e.get('confidence')}]")
    if not d.get("startup_flow") and not eps:
        L.append("> 未建立执行路径。[Unknown / Needs verification]")

    L += _section("6. Key Data / Control Flows")
    structs = d.get("type_structs", [])
    if structs:
        L.append("关键数据模型（type_semantics，Fact）:")
        L.append("| Struct | File | Line |")
        L.append("|---|---|---:|")
        for s in structs[:30]:
            L.append(f"| `{s.get('name')}` | `{s.get('file')}` | {s.get('line')} |")
    else:
        L.append("> 无类型语义数据。[Unknown]")

    L += _section("7. Callback / Indirect Call Areas")
    inds = d.get("indirect_areas", [])
    if inds:
        L.append("（函数注册/绑定事实，不承诺真实调用路径）[Fact]")
        L.append("| File | Via | Callee |")
        L.append("|---|---|---|")
        for e in inds[:20]:
            L.append(f"| `{e['file']}` | {e['via']} | `{e['callee']}` |")
    else:
        L.append("> 无间接调用/回调注册记录。[Unknown]")

    L += _section("8. Build Boundary")
    b = d.get("build", {})
    L.append(f"- Target: `{b.get('target') or 'unknown'}` [Fact]")
    L.append(f"- Targets: `{', '.join(str(x) for x in b.get('targets') or []) or 'unknown'}`")
    L.append(f"- Compiled files: `{b.get('compiled_count')}` [Fact]")
    L.append(f"- Project files: `{b.get('project_files')}` [Fact]")

    L += _section("9. Important Architectural Constraints")
    if d.get("uncertain"):
        L.append("本版未自动提出约束；以下为不确定性记录（[Unknown]）：")
        for u in d["uncertain"][:8]:
            L.append(f"- {u}")
    else:
        L.append("> 未从当前 Index 提炼出明确约束。[Unknown]")

    L += _section("10. Module Dependency Graph (Evidence-backed)")
    L.extend(_mermaid_flow(d.get("module_dependencies", [])))

    L += traceability_table(
        [
            ("Build target", f"{b.get('target') or '?'} / compiled={b.get('compiled_count')}"),
            ("Major modules", f"{len(d.get('modules', []))} project modules"),
            ("Module dependencies", f"{len(deps)} edges [Index dependencies]"),
        ]
    )
    return "\n".join(L) + "\n"


# ---------- MODULES ----------


def render_modules(bundle: Any, index: Any, project_root_name: str, prose: str = "") -> str:
    data = bundle.module_knowledge()
    L: list[str] = []
    L.append("# Modules")
    L.append("")
    L.extend(metadata_header(index, project_root_name))
    L.append("")
    L.append("> AgentX Human Project Knowledge — Module Responsibilities")
    L.append(">")
    L.append("> HIGH → 直接表达；MEDIUM → 明确 [Inference]；LOW → 仅 Module Map。")

    L += _section("Module Map")
    L.append("| Module | Responsibility | Confidence | Scope | Build | Files | Symbols |")
    L.append("|---|---|---:|---|---|---:|---:|")
    for r in data["map"]:
        scope = str(r.get("scope_type", "project"))
        if scope != "project":
            scope_label = {
                "third_party": "third-party",
                "non_build": "not in target",
                "ignored": "ignored",
            }.get(scope, scope)
        else:
            scope_label = "project"
        resp = str(r.get("responsibility") or "-").replace("|", "\\|")
        if r.get("third_party"):
            resp = "(third-party)"
        elif r.get("generated_by") != "llm" and resp and "符号" in resp:
            # fallback 保守描述不适合 map 单行——以结构性摘要替代职责声明
            resp = f"（{r['files']} 文件 / {r['symbols']} 符号；职责未判断）"
        elif not resp:
            resp = "-"
        L.append(
            f"| `{r['name']}` | {resp[:80]} | {r['confidence']} | {scope_label} "
            f"| {r.get('build_status') or '-'} | {r['files']} | {r['symbols']} |"
        )

    L += _section("Module Details")
    if prose:
        L.append(prose)
    if not data["detail"]:
        L.append("> 无展开模块（缺少 project high/medium 模块）。")

    for m in data["detail"]:
        name = m["name"]
        conf = m["confidence"]
        L.append("")
        L.append(f"### {name}")
        L.append("")
        resp = str(m.get("responsibility") or "").strip()
        if resp:
            L.append("#### Responsibility")
            if m.get("generated_by") == "llm":
                L.append(f"{resp} {_tag_interpretation(conf)}")
            else:
                L.append(
                    f"{resp} "
                    "[事实构成（fallback）：未做业务职责判断，勿当作确定结论]"
                )
        else:
            L.append("#### Responsibility")
            L.append("> Unknown / Not established / Needs verification")

        L.append("")
        L.append("#### Entry Points")
        eps = m.get("entry_points") or []
        if eps:
            L.extend(f"- `{e}`" for e in eps)
        else:
            L.append("- (none)")
        L.append("")
        L.append("#### Main Consumers")
        cons = m.get("consumers") or []
        if cons:
            L.extend(f"- `{c}`" for c in cons)
        else:
            L.append("- (none)")
        L.append("")
        L.append("#### Dependencies")
        deps = m.get("dependencies") or []
        if deps:
            L.extend(f"- `{d}`" for d in deps)
        else:
            L.append("- (none)")
        L.append("")
        L.append("#### Important Symbols")
        syms = m.get("symbols") or []
        L.extend(f"- `{s}`" for s in syms[:16])
        if len(syms) > 16:
            L.append(f"- ... (+{len(syms) - 16} more)")
        L.append("")
        L.append("#### Build Status")
        stats = m.get("build_stats") or {}
        L.append(
            f"- `{m.get('build_status') or 'unknown'}` "
            f"(compiled {stats.get('compiled', 0)}/{stats.get('total', 0)})"
        )
        L.append("")
        L.append("#### Evidence")
        basis = m.get("evidence_basis") or []
        if basis:
            L.extend(f"- `{b}`" for b in basis)
        else:
            L.append("- (no evidence basis)")
        L.append("")
        L.append("#### Uncertainty")
        if conf == "low":
            L.append("- LOW confidence：仅为路径/命名构成，未做职责判断。")
        elif m.get("generated_by") == "fallback":
            L.append("- 职责为 fallback 保守描述（未用 LLM），不构成确定业务结论。")
        if m.get("build_status") == "not_compiled":
            L.append("- 该模块文件不在当前 build target 的编译列表内。")

    L.append("")
    L.append("## Traceability")
    L.append("")
    L.append("| Module | Evidence file |")
    L.append("|---|---|")
    for m in data["detail"]:
        files = m.get("files") or []
        if files:
            L.append(f"| `{m['name']}` | `{files[0]}` |")

    return "\n".join(L) + "\n"


def render_document(
    doc_name: str,
    bundle: Any,
    index: Any,
    project_root_name: str,
    prose: str = "",
) -> str:
    """按文档类型渲染（prose 为可选的 LLM 语言组织，空则纯确定性）。"""
    if doc_name == DOC_PROJECT_OVERVIEW:
        return render_project_overview(bundle, index, project_root_name, prose=prose)
    if doc_name == DOC_ARCHITECTURE:
        return render_architecture(bundle, index, project_root_name, prose=prose)
    if doc_name == DOC_MODULES:
        return render_modules(bundle, index, project_root_name, prose=prose)
    raise ValueError(f"未知文档: {doc_name}")


__all__ = [
    "render_project_overview",
    "render_architecture",
    "render_modules",
    "render_document",
    "metadata_header",
    "RESPONSIBILITIES_FILENAME",
]
